### ISSUE TITLE
formulaire : create event , remplacer le code postal par un auto complete Ville

### ISSUE THREAD

**Issue by oceatoon** [pixelhumain/communEvent#28]
on se rend compte que c'est vraiment pourri le remplissage par CP 
il faudrait qu'on fasse simplement unautocomplete sur les nom de ville 
ce sera bcp plus simple 
car quand tu veux ajouter un evennement et qu'on connait pas le CP bah on est coincé

**Comment by aboire** [comment]
j'ai fait pour le moment une auto detection de l'endroit ou on est pour preremplir

**Comment by oceatoon** [comment]
l'idée à terme c'est de le faire marcher a l'international directe , 
qu'il ny ait pas de restriction  sur les country de notre DB
